### ISSUE TITLE
Departments in Registration page

### ISSUE THREAD

**Issue by cmanda** [rathnapandi/runners#30]
- PSO & CSMs
- Sales & Presales
- R&D
- Product Line
- People & Culture
- Global Support

**Comment by cmanda** [comment]
- PSO & CSMs
- Sales & Presales
- R&D
- Product Line
- People & Culture
- Global Support
- Marketing
- Legal
- IT/IS
- Other

**Comment by rathnapandi** [comment]
Fixed
